### PR TITLE
WIP: bounty assistance

### PR DESCRIPTION
**Pull request by delphiactual**
generate data to assist with
https://github.com/DestinyItemManager/DIM/issues/3868

### CODE REVIEW

**Comment by delphiactual** [comment]
need to account for multiple locations, enemies, weapons, and damage type

**Comment by delphiactual** [comment]
need to figure out where to put `generate orbs`

**Comment by sundevour** [comment]
https://github.com/delphiactual/d2-additional-info/pull/15/commits/b48ce01705c74c6737e6c04e2a11c687fceb4158
fixes fusion rifle catching LFR, seen in bounty 4116535682

**Comment by delphiactual** [comment]
bounty `164712560` identifying as enemy vex; does not appear to be.
`Har-Vex-ting Resources - Harvest Datalattice on Nessus or Simulation Seeds on Mercury.`
Harvest with play on words for Vex...

**Comment by delphiactual** [comment]
bounty `319649229` Energy or Power weapons

**Comment by delphiactual** [comment]
bounty `351381400` might need to look into making strike specific category as well

**Pull request closed without merging**
